name: weather_app
description: "The main concept of this app is to combine dark, offensive and
  ridiculous humor with everyday forecast."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  provider: ^6.1.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 